### ISSUE TITLE
Incorrect figma style value bg.canvas.default

### ISSUE THREAD

**Issue by germain-gg** [vector-im/compound#262] opened 2023-10-30 14:36 UTC
# Platform

- Design tokens

# Description

@jmartinesp says the dark variant of the "bg canvas default" color should be `#1d1f24` backed by https://github.com/vector-im/compound-design-tokens/blob/main/tokens/theme-semantics-dark.json#L11

Whilst @callumu says it should be `#101317` backed by https://www.figma.com/file/PpKepmHKGikp33Ql7iivbn/Compound-Styles?type=design&node-id=1203-654&mode=design&t=eDh1AiNGAAtKWWOv-11

**Comment by janogarcia** [comment] 2023-10-30 15:28
`bg.canvas.default` and `bg.canvas.default-level-1` are different semantic tokens. While they point to the same hex value in Light theme, they should point to two different hex values in Dark theme.

### bg.canvas.default

The current mapping for `bg.canvas.default` is correct.

It points to [`color.theme.bg`](https://github.com/vector-im/compound-design-tokens/blob/70187549580fc41f6aa3dab926f48f9441372cd9/tokens/theme-semantics.json#L85) for both themes. That is, that semantic token is symmetrical. 

The value for `color.theme.bg` in Dark mode is [`#101317`](https://github.com/vector-im/compound-design-tokens/blob/9a6321ba7db2724b8af510145e0e2142821b66d6/tokens/theme-dark.json#L5).

### bg.canvas.default-level-1

The semantic token @jmartinesp is referring to, `bg.canvas.default-level-1` is a completely different one. In Dark mode it points to `color.gray.300` which translates to `#1d1f24`, and that's expected given that it's asymmetrical ([light](https://github.com/vector-im/compound-design-tokens/blob/70187549580fc41f6aa3dab926f48f9441372cd9/tokens/theme-semantics-light.json) vs [dark](https://github.com/vector-im/compound-design-tokens/blob/70187549580fc41f6aa3dab926f48f9441372cd9/tokens/theme-semantics-dark.json)).

**Comment by janogarcia** [comment] 2023-10-30 15:32
I'm closing this issue as it's working as intended, but feel free to reopen if necessary.

**Closed by janogarcia** 2023-10-30 15:32 UTC
Labels: T-Defect
